name: iosbackup
version: '1.0.0'
summary: Cisco IOS config backup tool
description: |
  Simple utility for backing up Cisco IOS configuration.

confinement: strict
grade: stable
base: core18

parts:
  rosbackup:
    plugin: python
    python-version: python3
    source: https://github.com/mharjac/iosbackup.git
    source-type: git

apps:
  iosbackup:
    command: bin/iosbackup
    plugs:
      - network
      - home
    environment:
      LANG: C.UTF-8

